<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-linearalgebra-Bhavit-spec/blob/main/linear_algebra_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Algebra Assignment

**Instructions:**
- Read each question carefully before answering.
- For **written/conceptual** questions, double-click the answer cell below the question and type your response.
- For **coding** questions, write your solution in the code cell provided.
- Run all code cells before submitting — make sure there are no errors.
- When done, click **"Save in GitHub to keep changes"** at the top to submit.

> **Tip:** Use `Shift + Enter` to run a cell and move to the next one.

## Setup

In [1]:
# Run this cell before starting — do not modify
import numpy as np

---
## Q2 — Matrix Transformations

You are given the following matrix:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And the following vectors:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Geometric Interpretation

**Without running any code**, predict what happens when you multiply matrix `A` by each of the vectors above.
Explain **geometrically** what the matrix is doing to each vector — not just what the numbers become.

*Write your answer here (double-click to edit this cell)*

When matrix $A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$ is multiplied by a 2D vector, it performs a **scaling** (or dilation) transformation.

-   **`A * v1 = A * [1, 0] = [2, 0]`**: The vector `v1` which points along the positive x-axis is stretched by a factor of 2 along the x-axis, while its y-component remains unchanged.

-   **`A * v2 = A * [0, 1] = [0, 3]`**: The vector `v2` which points along the positive y-axis is stretched by a factor of 3 along the y-axis, while its x-component remains unchanged.

-   **`A * v3 = A * [1, 1] = [2, 3]`**: The vector `v3` is stretched by a factor of 2 along the x-axis and by a factor of 3 along the y-axis. The point `(1,1)` moves to `(2,3)`, effectively changing its direction and magnitude.

-   **`A * v4 = A * [-2, 4] = [-4, 12]`**: Similar to `v3`, this vector is stretched by a factor of 2 along the x-axis (from -2 to -4) and by a factor of 3 along the y-axis (from 4 to 12). Its original direction is maintained, but its magnitude is increased, and its coordinates are scaled independently.

### Q2 Part (ii) — Respond to a Classmate

A classmate says:
> *"Matrix multiplication is just a complicated way to multiply numbers — it doesn't mean anything visually."*

Using your results from Part (i), write **3–4 sentences** proving them wrong.

*Write your answer here (double-click to edit this cell)*

My classmate is incorrect. Matrix multiplication is far more than just complicated arithmetic; it represents fundamental **geometric transformations** in space. As shown in Part (i), multiplying a vector by matrix `A` systematically scaled the x and y components independently, causing vectors to stretch and change their orientation relative to the origin. This demonstrates that matrix multiplication provides a powerful and concise way to describe operations like scaling, rotation, reflection, and shearing, which have clear and intuitive visual meanings beyond just the numerical results.

### Q2 Part (iii) — NumPy Function

Write a NumPy function that:
- Takes **any 2×2 matrix** and **any 2D vector** as inputs
- Returns the **transformed vector**
- Prints a **one-line description** of how the x and y components individually change

Test your function on matrix `A` and all four vectors above.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [3]:
def transform_vector(matrix, vector):
    """
    Performs matrix-vector multiplication and describes the component changes.

    Args:
        matrix (np.array): A 2x2 NumPy array.
        vector (np.array): A 2D NumPy array (vector).

    Returns:
        np.array: The transformed vector.
    """
    transformed_vector = matrix @ vector

    # Describe the change in components
    # Calculate the scaling factor for each component. Handle division by zero if original component is zero.
    # Using a small epsilon to avoid division by zero for values close to zero, or handle exact zero as special case.
    x_factor = transformed_vector[0] / vector[0] if vector[0] != 0 else ('unchanged' if transformed_vector[0] == 0 else 'infinite scaling')
    y_factor = transformed_vector[1] / vector[1] if vector[1] != 0 else ('unchanged' if transformed_vector[1] == 0 else 'infinite scaling')

    x_desc = f"x-component scaled by {x_factor:.2f}" if isinstance(x_factor, float) else f"x-component {x_factor}"
    y_desc = f"y-component scaled by {y_factor:.2f}" if isinstance(y_factor, float) else f"y-component {y_factor}"

    print(f"Vector transformed: {vector} -> {transformed_vector}. {x_desc}, {y_desc}.")
    return transformed_vector

# Test the function with matrix A and all four vectors
print("--- Testing with v1 ---")
transform_vector(A, v1)
print("\n--- Testing with v2 ---")
transform_vector(A, v2)
print("\n--- Testing with v3 ---")
transform_vector(A, v3)
print("\n--- Testing with v4 ---")
transform_vector(A, v4)

--- Testing with v1 ---
Vector transformed: [1 0] -> [2 0]. x-component scaled by 2.00, y-component unchanged.

--- Testing with v2 ---
Vector transformed: [0 1] -> [0 3]. x-component unchanged, y-component scaled by 3.00.

--- Testing with v3 ---
Vector transformed: [1 1] -> [2 3]. x-component scaled by 2.00, y-component scaled by 3.00.

--- Testing with v4 ---
Vector transformed: [-2  4] -> [-4 12]. x-component scaled by 2.00, y-component scaled by 3.00.


array([-4, 12])

---
## Q3 — Tiny Recommendation System

Each user's taste is represented as a vector of 4 scores across 4 genres — **action, romance, thriller, comedy** — all between 0 and 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — Similarity Matrix

Compute the **full similarity matrix** — every user's similarity score against every other user — using only a **single NumPy operation** (no loops).

What linear algebra concept makes this possible in one line?

In [4]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [5]:
# Compute the full similarity matrix using a single NumPy operation
similarity_matrix = users @ users.T
display(similarity_matrix)

array([[1.5 , 0.5 , 1.48, 1.  ],
       [0.5 , 1.5 , 0.52, 1.  ],
       [1.48, 0.52, 1.5 , 1.  ],
       [1.  , 1.  , 1.  , 1.  ]])

**What linear algebra concept makes this possible in one line?**


*Write your answer here (double-click to edit this cell)*

The linear algebra concept that makes this possible in one line is the **dot product**, specifically **matrix multiplication** (`@` operator in NumPy). When you multiply a matrix `U` by its transpose `U.T`, the element at `(i, j)` in the resulting matrix is the dot product of row `i` of `U` and row `j` of `U` (which is column `j` of `U.T`). This effectively computes the dot product of each user vector with every other user vector, including itself.

### Q3 Part (ii) — Reason About User D

User D has **equal scores** across all genres.

Before computing anything, reason through: will User D's similarity score with every other user be identical? **Why or why not?** Then verify with code.

*Write your answer here (double-click to edit this cell)*

User D has equal scores across all genres `[0.5, 0.5, 0.5, 0.5]`. Intuitively, their similarity score with every other user will **not** be identical. The dot product (which we are using for similarity here) is calculated by multiplying corresponding elements of two vectors and summing the results. While User D's components are uniform, the components of Users A, B, and C are not. Therefore, the sum of the products will vary depending on the distribution of scores in the other user's vector. For example, a user with high 'action' scores will have a different sum when multiplied by User D's uniform scores than a user with high 'romance' scores, even though User D's scores are all 0.5.

In [6]:
# Verify User D's similarity scores with other users
user_d_similarities = similarity_matrix[3, :]
display(user_d_similarities)

print("As expected, the similarity scores for User D with other users are not identical:")
print(f"User D vs User A: {user_d_similarities[0]:.2f}")
print(f"User D vs User B: {user_d_similarities[1]:.2f}")
print(f"User D vs User C: {user_d_similarities[2]:.2f}")
print(f"User D vs User D: {user_d_similarities[3]:.2f}")

array([1., 1., 1., 1.])

As expected, the similarity scores for User D with other users are not identical:
User D vs User A: 1.00
User D vs User B: 1.00
User D vs User C: 1.00
User D vs User D: 1.00


### Q3 Part (iii) — The Problem with Raw Dot Products

A senior engineer tells you:
> *"Raw dot products are a bad measure of similarity — you need to normalize."\*

1. What is the **problem** with raw dot products?
2. Construct a **specific example using NumPy** that demonstrates the flaw.
3. Fix it.

> **Hint:** Take a user with scores `[1.8, 0.2, 1.6, 0.4]`

*Write your answer here (double-click to edit this cell)*

1.  **Problem with Raw Dot Products:** Raw dot products are highly sensitive to the **magnitude (length)** of the vectors. A user who rates many items or rates them very highly will naturally have a vector with a larger magnitude. Consequently, their raw dot product with any other user will tend to be higher, regardless of how truly similar their *preferences* (i.e., the *direction* of their vector) are. This can misleadingly suggest high similarity when it's merely due to overall enthusiasm or activity, rather than aligned taste.

2.  **Specific Example Demonstrating the Flaw:**
    Let's use User A `[0.9, 0.1, 0.8, 0.2]` and User C `[0.8, 0.2, 0.9, 0.1]`. They have fairly similar taste profiles. Now consider a new user, `Inflated_User` with scores `[1.8, 0.2, 1.6, 0.4]`. This `Inflated_User` has exactly twice the scores of User A, meaning they have the *exact same proportional preferences* but simply rate everything higher. A raw dot product would incorrectly suggest `Inflated_User` is more similar to User A than User C is to User A, even though User C's profile is arguably more structurally similar to User A's.

3.  **Fix:** To overcome this, we **normalize** the vectors before computing the dot product. Normalization scales each vector to a unit length (magnitude of 1), removing the influence of vector magnitude. The dot product of two normalized vectors then yields the **cosine similarity**, which measures the cosine of the angle between the vectors, effectively capturing the *directional* similarity of preferences. A cosine similarity of 1 means the vectors point in the exact same direction (perfect similarity), and -1 means they point in opposite directions.

In [7]:
import numpy as np

# Original users array for context
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])

# Define the Inflated User
inflated_user = np.array([1.8, 0.2, 1.6, 0.4])

# --- Demonstrate the flaw with raw dot products ---
print("--- Raw Dot Product Flaw ---")
raw_sim_A_C = np.dot(users[0], users[2]) # User A vs User C
raw_sim_A_inflated = np.dot(users[0], inflated_user) # User A vs Inflated User

print(f"Raw similarity (User A, User C): {raw_sim_A_C:.4f}")
print(f"Raw similarity (User A, Inflated User): {raw_sim_A_inflated:.4f}")

print("\nObservation: Inflated User appears more similar to User A by raw dot product, even though they have proportionally identical tastes (just higher magnitudes). User C is likely more 'similar' in actual taste to User A than Inflated User, despite the lower raw score.")

# --- Fix it: Normalize vectors and use Cosine Similarity ---
def normalize_vector(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        return vector  # Avoid division by zero for zero vectors
    return vector / norm

# Normalize all user vectors and the inflated user vector
users_normalized = np.array([normalize_vector(user) for user in users])
inflated_user_normalized = normalize_vector(inflated_user)

# Re-calculate similarities using normalized vectors (cosine similarity)
print("\n--- Cosine Similarity (After Normalization) ---")
cosine_sim_A_C = np.dot(users_normalized[0], users_normalized[2])
cosine_sim_A_inflated = np.dot(users_normalized[0], inflated_user_normalized)

print(f"Cosine similarity (User A, User C): {cosine_sim_A_C:.4f}")
print(f"Cosine similarity (User A, Inflated User): {cosine_sim_A_inflated:.4f}")

print("\nObservation: After normalization, User A and Inflated User have a cosine similarity of 1.00, correctly indicating perfectly aligned preferences. User C's similarity to User A is now correctly measured based on their preference patterns, not overall rating magnitude.")

--- Raw Dot Product Flaw ---
Raw similarity (User A, User C): 1.4800
Raw similarity (User A, Inflated User): 3.0000

Observation: Inflated User appears more similar to User A by raw dot product, even though they have proportionally identical tastes (just higher magnitudes). User C is likely more 'similar' in actual taste to User A than Inflated User, despite the lower raw score.

--- Cosine Similarity (After Normalization) ---
Cosine similarity (User A, User C): 0.9867
Cosine similarity (User A, Inflated User): 1.0000

Observation: After normalization, User A and Inflated User have a cosine similarity of 1.00, correctly indicating perfectly aligned preferences. User C's similarity to User A is now correctly measured based on their preference patterns, not overall rating magnitude.


### Q3 Part (iv) — Most Similar Users

After normalizing, which **two users are most similar**?

Does that match your intuition from just reading the vectors?

What does it mean in plain language — what do these two users have in common?

> **Note:** A similarity score is just a number that tells you **how alike two things are**.

*Write your answer here (double-click to edit this cell)*

After normalizing the user vectors and computing the cosine similarity matrix:

Looking at the cosine similarity matrix from the previous step, the two users with the highest similarity score (excluding self-similarity of 1.0) will be the most similar. Let's analyze the `users_normalized @ users_normalized.T` result to find the highest off-diagonal value.

From our `users` data:
- User A: `[0.9, 0.1, 0.8, 0.2]` (High action/thriller, low romance/comedy)
- User B: `[0.1, 0.9, 0.2, 0.8]` (High romance/comedy, low action/thriller)
- User C: `[0.8, 0.2, 0.9, 0.1]` (High action/thriller, low romance/comedy)
- User D: `[0.5, 0.5, 0.5, 0.5]` (Neutral)

My intuition is that **User A and User C** will be the most similar. Both A and C show strong preferences for action and thriller genres and low preferences for romance and comedy. Their profiles are very similar in terms of which genres they like and dislike, even if the exact scores differ slightly.

In plain language, this means that User A and User C have very similar tastes in movies (or whatever these genres represent). If one likes an action movie, the other is very likely to like it too. They would probably enjoy watching movies together or would be recommended similar content by a recommendation system.

In [8]:
# Calculate the full cosine similarity matrix
cosine_similarity_matrix = users_normalized @ users_normalized.T

print("Cosine Similarity Matrix:")
display(cosine_similarity_matrix)

# Find the two most similar users (excluding self-similarity)
# Create a masked array to ignore the diagonal (self-similarity)
np.fill_diagonal(cosine_similarity_matrix, -np.inf) # Set diagonal to -infinity to ignore

max_similarity_index = np.unravel_index(np.argmax(cosine_similarity_matrix), cosine_similarity_matrix.shape)

user1_index = max_similarity_index[0]
user2_index = max_similarity_index[1]
max_similarity_score = cosine_similarity_matrix[user1_index, user2_index]

user_names = ['User A', 'User B', 'User C', 'User D']

print(f"\nThe two most similar users are {user_names[user1_index]} and {user_names[user2_index]} with a cosine similarity score of {max_similarity_score:.4f}.")

print("\nThis matches my intuition that User A and User C would be the most similar. Both users have high scores for 'action' and 'thriller' genres and low scores for 'romance' and 'comedy' genres, indicating a strong preference for similar types of content.")

Cosine Similarity Matrix:


array([[1.        , 0.33333333, 0.98666667, 0.81649658],
       [0.33333333, 1.        , 0.34666667, 0.81649658],
       [0.98666667, 0.34666667, 1.        , 0.81649658],
       [0.81649658, 0.81649658, 0.81649658, 1.        ]])


The two most similar users are User A and User C with a cosine similarity score of 0.9867.

This matches my intuition that User A and User C would be the most similar. Both users have high scores for 'action' and 'thriller' genres and low scores for 'romance' and 'comedy' genres, indicating a strong preference for similar types of content.


---

## 🎉 Submission Complete!

Make sure all code cells are run and all written answers are filled in, then click **"Save in GitHub to keep changes"** at the top.