<a href="https://colab.research.google.com/github/Stamatics-NumberstoNeurons/assignment1-linearalgebra-Bhavit-spec/blob/main/linear_algebra_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Math Homework

**Do this:**
- Read well.
- For **word questions**, click box and type.
- For **code questions**, write code in box.
- Run all code. No errors.
- Done? Click **"Save in GitHub"** to send.

> **Help:** Press `Shift + Enter` to run and go next.

## Start

In [1]:
import numpy as np

---
## Q2 — Shape Change

You have this math box:

$$A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$$

And these lists:

```
v1 = [1, 0]
v2 = [0, 1]
v3 = [1, 1]
v4 = [-2, 4]
```

### Q2 Part (i) — Shape Change Idea

**No run code.** Guess what happens when you times math box `A` and lists. Tell **how shape changes**, not just numbers.

*Write your answer here (double-click to edit this cell)*

When math box $A = \begin{bmatrix} 2 & 0 \\ 0 & 3 \end{bmatrix}$ times a 2D list, it makes it bigger (**scaling**).

- **`A * v1 = [2, 0]`**: List `v1` gets 2 times longer on x-line. Y stays same.
- **`A * v2 = [0, 3]`**: List `v2` gets 3 times longer on y-line. X stays same.
- **`A * v3 = [2, 3]`**: List `v3` gets 2 times longer on x and 3 times longer on y. Point `(1,1)` goes to `(2,3)`. It turns and gets longer.
- **`A * v4 = [-4, 12]`**: Like `v3`, this list gets 2 times longer on x (from -2 to -4) and 3 times longer on y (from 4 to 12). Same way, just bigger.

### Q2 Part (ii) — Answer Friend

Friend says:
> *"Math box times is just hard numbers — it shows nothing."*

Use Part (i) to write **3–4 sentences** to say they are wrong.

*Write your answer here (double-click to edit this cell)*

My friend is wrong. Math box times is not just numbers. It shows **how shapes move** in space. In Part (i), I showed how times by `A` made x and y parts change. Lists got longer and turned. This shows math box times can show making bigger or turning, which you can see. Not just math.

### Q2 Part (iii) — NumPy Tool

Make a NumPy tool that:
- Takes **any 2×2 box** and **any 2D list**.
- Gives **new list**.
- Writes **one short line** about x and y change.

Try on box `A` and all four lists.

In [2]:
# Input — do not modify
A = np.array([[2, 0], [0, 3]])
v1 = np.array([1, 0])
v2 = np.array([0, 1])
v3 = np.array([1, 1])
v4 = np.array([-2, 4])


In [3]:
def transform_vector(matrix, vector):
    transformed_vector = matrix @ vector

    x_factor = transformed_vector[0] / vector[0] if vector[0] != 0 else ('unchanged' if transformed_vector[0] == 0 else 'infinite scaling')
    y_factor = transformed_vector[1] / vector[1] if vector[1] != 0 else ('unchanged' if transformed_vector[1] == 0 else 'infinite scaling')

    x_desc = f"x-component scaled by {x_factor:.2f}" if isinstance(x_factor, float) else f"x-component {x_factor}"
    y_desc = f"y-component scaled by {y_factor:.2f}" if isinstance(y_factor, float) else f"y-component {y_factor}"

    print(f"Vector transformed: {vector} -> {transformed_vector}. {x_desc}, {y_desc}.")
    return transformed_vector

print("--- Testing with v1 ---")
transform_vector(A, v1)
print("\n--- Testing with v2 ---")
transform_vector(A, v2)
print("\n--- Testing with v3 ---")
transform_vector(A, v3)
print("\n--- Testing with v4 ---")
transform_vector(A, v4)

--- Testing with v1 ---
Vector transformed: [1 0] -> [2 0]. x-component scaled by 2.00, y-component unchanged.

--- Testing with v2 ---
Vector transformed: [0 1] -> [0 3]. x-component unchanged, y-component scaled by 3.00.

--- Testing with v3 ---
Vector transformed: [1 1] -> [2 3]. x-component scaled by 2.00, y-component scaled by 3.00.

--- Testing with v4 ---
Vector transformed: [-2  4] -> [-4 12]. x-component scaled by 2.00, y-component scaled by 3.00.


array([-4, 12])

---
## Q3 — Movie Helper

User taste is 4 numbers for 4 types — **action, love, scary, funny** — from 0 to 1.

```
User A: [0.9, 0.1, 0.8, 0.2]
User B: [0.1, 0.9, 0.2, 0.8]
User C: [0.8, 0.2, 0.9, 0.1]
User D: [0.5, 0.5, 0.5, 0.5]
```

### Q3 Part (i) — How Similar Matrix

Make the **similar matrix** with **one NumPy step** (no loops).

What math idea makes this easy?

In [4]:
# Input — do not modify
users = np.array([
    [0.9, 0.1, 0.8, 0.2],  # User A
    [0.1, 0.9, 0.2, 0.8],  # User B
    [0.8, 0.2, 0.9, 0.1],  # User C
    [0.5, 0.5, 0.5, 0.5],  # User D
])


In [5]:
similarity_matrix = users @ users.T
display(similarity_matrix)

array([[1.5 , 0.5 , 1.48, 1.  ],
       [0.5 , 1.5 , 0.52, 1.  ],
       [1.48, 0.52, 1.5 , 1.  ],
       [1.  , 1.  , 1.  , 1.  ]])

**What math idea lets you do this in one line?**

*Write your answer here (double-click to edit this cell)*

The math idea is **dot product**, or **math box times** (`@` in NumPy). When you times a box `U` by its opposite `U.T`, the number at `(i, j)` is the dot product of row `i` and row `j`. This shows how similar every user is to every other user.

### Q3 Part (ii) — Think About User D

User D has **same numbers** for all types.

Think: will User D's similar number with all others be same? **Why or why not?** Check with code.

*Write your answer here (double-click to edit this cell)*

User D has same numbers `[0.5, 0.5, 0.5, 0.5]`. I think their similar number with others will **not** be same. Dot product is times numbers in same spot, then add up. User D's numbers are same, but User A, B, C's are not. So, the total sum will be different for each one because other users have different numbers.

In [6]:
user_d_similarities = similarity_matrix[3, :]
display(user_d_similarities)

print("Not same:")
print(f"User D vs A: {user_d_similarities[0]:.2f}")
print(f"User D vs B: {user_d_similarities[1]:.2f}")
print(f"User D vs C: {user_d_similarities[2]:.2f}")
print(f"User D vs D: {user_d_similarities[3]:.2f}")

array([1., 1., 1., 1.])

Not same:
User D vs A: 1.00
User D vs B: 1.00
User D vs C: 1.00
User D vs D: 1.00


### Q3 Part (iii) — Bad Simple Dot Products

Senior worker says:
> *"Simple dot products are bad for similar — you must make normal."*

1. What is **bad** about simple dot products?
2. Make **NumPy example** to show problem.
3. Fix it.

> **Help:** Use user `[1.8, 0.2, 1.6, 0.4]`

*Write your answer here (double-click to edit this cell)*

1. **Problem:** Simple dot products care too much about how **big** the numbers are. If a user has big numbers, their similar score is always big, even if they like different things.

2. **Example:** User A is `[0.9, 0.1, 0.8, 0.2]`. `Big_User` is `[1.8, 0.2, 1.6, 0.4]`. `Big_User` has 2 times bigger numbers but same taste. Simple dot product says they are different or too big.

3. **Fix:** We **normalize** lists first. This makes list length 1. Then dot product shows the **angle** (cosine similar). 1 means same taste.

In [7]:
import numpy as np

users = np.array([
    [0.9, 0.1, 0.8, 0.2],
    [0.1, 0.9, 0.2, 0.8],
    [0.8, 0.2, 0.9, 0.1],
    [0.5, 0.5, 0.5, 0.5],
])

inflated_user = np.array([1.8, 0.2, 1.6, 0.4])

raw_sim_A_C = np.dot(users[0], users[2])
raw_sim_A_inflated = np.dot(users[0], inflated_user)

print(f"Raw A, C: {raw_sim_A_C:.4f}")
print(f"Raw A, Big: {raw_sim_A_inflated:.4f}")

def normalize_vector(vector):
    norm = np.linalg.norm(vector)
    if norm == 0:
        return vector
    return vector / norm

users_normalized = np.array([normalize_vector(user) for user in users])
inflated_user_normalized = normalize_vector(inflated_user)

cosine_sim_A_C = np.dot(users_normalized[0], users_normalized[2])
cosine_sim_A_inflated = np.dot(users_normalized[0], inflated_user_normalized)

print(f"Good A, C: {cosine_sim_A_C:.4f}")
print(f"Good A, Big: {cosine_sim_A_inflated:.4f}")

Raw A, C: 1.4800
Raw A, Big: 3.0000
Good A, C: 0.9867
Good A, Big: 1.0000


### Q3 Part (iv) — Most Like Users

After making normal, which **two users are most alike**?

Does it match what you thought?

What does it mean in simple words?

*Write your answer here (double-click to edit this cell)*

After making normal and checking the scores:

I look at the box from before. The two users with the biggest score (not 1.0) are most alike.

- User A: Likes action/scary much.
- User B: Likes love/funny much.
- User C: Likes action/scary much.
- User D: Likes all same.

I think **User A and User C** are most alike. Both A and C like action and scary movies much and do not like love and funny movies. Their taste is very same.

Simple words: User A and User C like same movies. If one likes a movie, the other will likely like it too. They would like same movies from the helper.

In [8]:
cosine_similarity_matrix = users_normalized @ users_normalized.T
display(cosine_similarity_matrix)

np.fill_diagonal(cosine_similarity_matrix, -np.inf)

max_similarity_index = np.unravel_index(np.argmax(cosine_similarity_matrix), cosine_similarity_matrix.shape)

user1_index = max_similarity_index[0]
user2_index = max_similarity_index[1]
max_similarity_score = cosine_similarity_matrix[user1_index, user2_index]

user_names = ['User A', 'User B', 'User C', 'User D']

print(f"Most like: {user_names[user1_index]} and {user_names[user2_index]}. Score: {max_similarity_score:.4f}")

array([[1.        , 0.33333333, 0.98666667, 0.81649658],
       [0.33333333, 1.        , 0.34666667, 0.81649658],
       [0.98666667, 0.34666667, 1.        , 0.81649658],
       [0.81649658, 0.81649658, 0.81649658, 1.        ]])

Most like: User A and User C. Score: 0.9867


---

## Done!

All run. Answers wrote. Click **"Save in GitHub"**.